### ISSUE TITLE
Support for Mongo 3.6+ DNS seedlists `mongodb+srv://`

### ISSUE THREAD

**Issue by jon-king-mindbodyonline** [newrelic/nri-mongodb#39]
##### Support for Mongo 3.6+ DNS seedlists `mongodb+srv://`

The `globalsign/mbo` driver doesn't support `mongodb+srv://` seedlists. Related - request for `srv` support in the driver:
https://github.com/globalsign/mgo/issues/112

Would there be an issue with switching from `globalsign/mbo` to the driver [published by MongoDB](https://github.com/mongodb/mongo-go-driver), which already has support for the new connection string format?

**Comment by ccheek21** [comment]
Thanks for the request. It doesn't look like the official MongoDB driver is quite a drop in replacement, so it could be a fair bit of work to swap it out and verify that everything still works as expected. It's something that would be a possibility though. I'm not sure I'll have time to try this out anytime soon, but I'd be happy to review and test any PRs.

**Comment by kfalconer** [comment]
Similar to above, it is possible to specify multiple hosts? We are using Mongo Atlas and cant install NRI plugin on the host, but want to monitor from a different system. The `host` parameter seems to only accept one host name.

**Comment by jon-king-mindbodyonline** [comment]
@kfalconer You can manually list out all the cluster nodes in the `mongo-config.yml` that you drop in `/etc/newrelic-infra/integrations.d`. Ex:
```
integration_name: com.newrelic.mongodb

instances:
  - name: mongo-cluster-01-shard-00-00
    command: all
    arguments:
      host: mongo-cluster-01-shard-00-00-aa77zz.gcp.mongodb.net
      cluster_name: mongo-cluster-01
      port: 27017
      username: ##
      password: ##
      auth_source: admin
      ssl: true
      ssl_insecure_skip_verify: true
  - name: mongo-cluster-01-shard-00-01
    command: all
    arguments:
      host: mongo-cluster-01-shard-00-01-aa77zz.gcp.mongodb.net
      cluster_name: mongo-cluster-01
      port: 27017
      username: ##
      password: ##
      auth_source: admin
      ssl: true
      ssl_insecure_skip_verify: true
...
```
