### ISSUE TITLE
Fail to connect to Mongos on Sharded cluster in K8s

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/nri-mongodb#78]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

When monitoring a sharded clusters in K8s the integration fails to discover the `mongos` endpoint and no `MongosSample` is generated.

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

Mongos metrics collection endpoints are discovered in the integration but in K8s the `Id` on `collections.config.mongos` contains the Pod name which cannot be resolved by the integration. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )

Support native mongos autodiscovery for K8s environments

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

Using bitnami `mongo-sharded` chart and configured the integration with discovery to the mongos pod
```yaml
nri-mongodb:
        discovery:
          command:
            exec: /var/db/newrelic-infra/nri-discovery-kubernetes --port 10250 --tls
            match:
              label.app.kubernetes.io/component: mongos
        integrations:
          - name: nri-mongodb
            env:
              HOST: ${discovery.ip}
              ...
```
The integrations prints the error like:
`[ERR] Failed to connect to mongos server <mongos-pod-name>:27017: no reachable servers`
## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )
I workaround this by using creating a service in the Agent namespace that points to the mongos instance and which have the same name of the mongos pod (using StatefulSet kind to deploy mongos to have predictable pod names). But this was just for the propose of validate the issue.
